In [4]:
import time
import re
import numpy as np
import pandas as pd
import warnings;warnings.filterwarnings('ignore')
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder

In [5]:
df_train = pd.read_csv('train.csv', lineterminator = '\n')
df_test = pd.read_csv('test.csv', lineterminator = '\n')

In [6]:
df_train.head()

ID                                             review     label
0   1                       Jo bhi ap se tou behtar hoon  Negative
1   2          ya Allah meri sister Affia ki madad farma  Positive
2   3  Yeh khud chahta a is umar main shadi krna.  ha...  Negative
3   4        Tc ? Apky mun xe exe alfax achy nae lgty 😒💃  Negative
4   5                                               Good  Positive

In [7]:
df_train['label'] = df_train['label'].map({'Negative': 0, 'Positive': 1})
df_train.head()

ID                                             review  label
0   1                       Jo bhi ap se tou behtar hoon      0
1   2          ya Allah meri sister Affia ki madad farma      1
2   3  Yeh khud chahta a is umar main shadi krna.  ha...      0
3   4        Tc ? Apky mun xe exe alfax achy nae lgty 😒💃      0
4   5                                               Good      1

In [8]:
df_train['label'].value_counts()

1    3361
0    2967
Name: label, dtype: int64

In [9]:
df_train.isnull().sum()

ID        0
review    0
label     0
dtype: int64

In [10]:
df_test.head()

ID                                             review
0   1  Yaqoob Memon Ki Phansi Zalimana Ghair Insani H...
1   2                                  Sabit qadam rehna
2   3  Good decision on ko bhi aam shehryun ki tarah ...
3   4  Jo Shakhs ALLAH Aur Qayamat Per Eman Rakhta Ho...
4   5  Tm log veriat kohli ko ahmad shahzad k sath co...

In [11]:
numpy_array = df_train.as_matrix()
numpy_array_test = df_test.as_matrix()
numpy_array[:4]

array([[1, 'Jo bhi ap se tou behtar hoon', 0],
       [2, 'ya Allah meri sister Affia ki madad farma', 1],
       [3, 'Yeh khud chahta a is umar main shadi krna.  had ogi', 0],
       [4, 'Tc ? Apky mun xe exe alfax achy nae lgty 😒💃', 0]],
      dtype=object)

In [12]:
numpy_array

array([[1, 'Jo bhi ap se tou behtar hoon', 0],
       [2, 'ya Allah meri sister Affia ki madad farma', 1],
       [3, 'Yeh khud chahta a is umar main shadi krna.  had ogi', 0],
       ...,
       [6326, 'Korangi Me Shani Qatal ', 0],
       [6327,
        'Ma na suna ha lemon sa haddiyan kamzor hoti hn regular Lana sa?',
        0],
       [6328,
        'Ball poar jadooi giraft se inhe rafter aur swing ko qaboo karne ka hairat angez fun aata hai',
        1]], dtype=object)

In [13]:
numpy_array[6]

array([7,
       ' Commission aur kickback ka dor Dora raha, quomi assase koriyon ke mol farokhat keye gaye',
       0], dtype=object)

In [14]:
numpy_array[0]

array([1, 'Jo bhi ap se tou behtar hoon', 0], dtype=object)

In [15]:
numpy_array_test[115]

array([116, 'Kisi Roz Jo Meri Gali Se Ishq Ka Janaza Nikle '],
      dtype=object)

In [16]:
numpy_array_test.size

5424

In [25]:
def cleaner(word):
    word = re.sub(r'\#\.', '', word)
    word = re.sub(r'\n', '', word)
    word = re.sub(r',', '', word)
    word = re.sub(r'\-', ' ', word)
    word = re.sub(r'\.', '', word)
    word = re.sub(r'\\', ' ', word)
    word = re.sub(r'\\x\.+', '', word)
    word = re.sub(r'\d', '', word)
    word = re.sub(r'^_.', '', word)
    word = re.sub(r'_', ' ', word)
    word = re.sub(r'^ ', '', word)
    word = re.sub(r' $', '', word)
    word = re.sub(r'\?', '', word)
    word = re.sub(r'é', '', word)
    word = re.sub(r'§', '', word)
    word = re.sub(r'¦', '', word)
    word = re.sub(r'æ', '', word)
    word = re.sub(r'\d+', '', word)
    word = re.sub('(.*?)\d+(.*?)', '', word)
    return word.lower()
def hashing(word):
    word = re.sub(r'ain$', r'ein', word)
    word = re.sub(r'ai', r'ae', word)
    word = re.sub(r'ay$', r'e', word)
    word = re.sub(r'ey$', r'e', word)
    word = re.sub(r'ie$', r'y', word)
    word = re.sub(r'^es', r'is', word)
    word = re.sub(r'a+', r'a', word)
    word = re.sub(r'j+', r'j', word)
    word = re.sub(r'd+', r'd', word)
    word = re.sub(r'u', r'o', word)
    word = re.sub(r'o+', r'o', word)
    word = re.sub(r'ee+', r'i', word)
    if not re.match(r'ar', word):
        word = re.sub(r'ar', r'r', word)
    word = re.sub(r'iy+', r'i', word)
    word = re.sub(r'ih+', r'eh', word)
    word = re.sub(r's+', r's', word)
    if re.search(r'[rst]y', 'word') and word[-1] != 'y':
        word = re.sub(r'y', r'i', word)
    if re.search(r'[bcdefghijklmnopqrtuvwxyz]i', word):
        word = re.sub(r'i$', r'y', word)
    if re.search(r'[acefghijlmnoqrstuvwxyz]h', word):
        word = re.sub(r'h', '', word)
    word = re.sub(r'k', r'q', word)
    return word

def array_cleaner(array):
    X = []
    for sentence in array:
        clean_sentence = ''
        words = sentence.split(' ')
        for word in words:
            clean_sentence = clean_sentence +  ' ' + cleaner(word)
        X.append(clean_sentence)
    return X

In [26]:
X_test = numpy_array_test[:, 1]
X_test

array(['Yaqoob Memon Ki Phansi Zalimana Ghair Insani Hai 20 Saal Qaid Kaat Chukay Thay Amnesty International Ki Bharti Iqdam Ki Muzammat ',
       ' Sabit qadam rehna',
       'Good decision on ko bhi aam shehryun ki tarah Huqooq hony chahye',
       ..., 'Lanat haramdyo', 'Is episode mein koi bhi hot nai hai',
       'Mery liye dua kry Allah pak naseeb achy kry ameen'], dtype=object)

In [27]:
counter = 1
for sentence in X_test:
    try:
        words = sentence.split(' ')
        counter += 1
    except:
        print(sentence)
        print(counter)

In [39]:
X_train = numpy_array[:, 1]
X_train = array_cleaner(X_train)
X_test = array_cleaner(X_test)
y_train = numpy_array[:, 2]
X_train[:5]

[' jo bhi ap se tou behtar hoon',
 ' ya allah meri sister affia ki madad farma',
 ' yeh khud chahta a is umar main shadi krna  had ogi',
 ' tc  apky mun xe exe alfax achy nae lgty 😒💃',
 ' good']

In [40]:
type(X_train)

list

In [41]:
type(X_test)

list

In [57]:
y_train = np.array(y_train)
y_train = y_train.astype('int8')
y_train[: 5]

array([0, 1, 0, 0, 1], dtype=int8)

In [58]:
ngram = 2
vectorizer = TfidfVectorizer(sublinear_tf = True, ngram_range = (1, ngram), max_df = 0.5)

In [59]:
X_all = X_train + X_test
lentrain = len(X_train)
vectorizer.fit(X_all)
X_all = vectorizer.transform(X_all)

In [60]:
X_train_chuli = X_all[: lentrain]
X_test_chuli = X_all[lentrain:]
X_train_chuli.shape

(6328, 113521)

In [64]:
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.linear_model import SGDClassifier as SGD

In [65]:
folds = StratifiedKFold(n_splits = 10, shuffle = False, random_state = 2019)
oof = np.zeros(X_train_chuli.shape[0])
predictions = np.zeros(X_test_chuli.shape[0])

In [66]:
for fold_, (trn_idx, val_idx) in enumerate(folds.split(X_train_chuli, y_train)):
    print('Fold : {}'.format(fold_ + 1))
    trn_data = X_train_chuli[trn_idx]
    trn_label = y_train[trn_idx]
    val_data = X_train_chuli[val_idx]
    val_label = y_train[val_idx]
    model_SGD = SGD(alpha = 0.00001, random_state = 2, shuffle = True, loss = 'log')
    model_SGD.fit(trn_data, trn_label)
    print('auc score: {:<8.5f}'.format(metrics.roc_auc_score(val_label, model_SGD.predict_proba(val_data)[:, 1])))
    predictions += model_SGD.predict_proba(X_test_chuli)[:, 1]

Fold : 1
auc score: 0.87129 
Fold : 2
auc score: 0.84598 
Fold : 3
auc score: 0.84839 
Fold : 4
auc score: 0.86017 
Fold : 5
auc score: 0.85166 
Fold : 6
auc score: 0.82702 
Fold : 7
auc score: 0.87713 
Fold : 8
auc score: 0.83738 
Fold : 9
auc score: 0.85027 
Fold : 10
auc score: 0.86954 


In [67]:
print(len(predictions))

2712


In [68]:
predictions[:4]

array([2.03836978, 5.20239239, 9.13164158, 7.4123612 ])